src/Axe/Models/ProfileViewModels/ChangePasswordViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Axe.Models.ProfileViewModels
{
    public class ChangePasswordViewModel
    {
        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Current password")]
        public string OldPassword { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "New password")]
        public string NewPassword { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm new password")]
        [Compare("NewPassword", ErrorMessage = "The new password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }
}

src/Axe/Models/ProfileViewModels/SetPasswordViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Axe.Models.ProfileViewModels
{
    public class SetPasswordViewModel
    {
        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "New password")]
        public string NewPassword { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm new password")]
        [Compare("NewPassword", ErrorMessage = "The new password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }
}

src/Axe/Controllers/ProfilesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using Microsoft.EntityFrameworkCore;
using Axe.Models;
using Axe.Models.ProfilesVm;

namespace Axe.Controllers
{
    [Authorize]
    public class ProfilesController : ControllerExt
    {
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly ILogger _logger;

        public ProfilesController(
          UserManager<ApplicationUser> userManager,
          SignInManager<ApplicationUser> signInManager,
          AxeDbContext context,
          ILoggerFactory loggerFactory)
            : base(userManager, context)
        {
            this.userManager = userManager;
            _signInManager = signInManager;
            this.context = context;
            _logger = loggerFactory.CreateLogger<ProfilesController>();
        }

        /// <summary>
        /// Return list of all registered users (possibly filtered)
        /// </summary>
        /// <param name="userFilter">Seacrh filter to match UserNames</param>
        /// <returns></returns>
        public async Task<IActionResult> Index(string userFilter = null)
        {
            IQueryable<ApplicationUser> userList = context.Users
                .Include(u => u.AssessmentsAsStudent).ThenInclude(a => a.Technology)
                .Include(u => u.Technologies).ThenInclude(t => t.Technology);

            if (false == String.IsNullOrWhiteSpace(userFilter))
                userList = userList.Where(u => u.UserName.Contains(userFilter) || u.Email.Contains(userFilter) || u.JobPosition.Contains(userFilter));

            ViewData[nameof(userFilter)] = userFilter;

            var data = (await userList.ToListAsync())
                .Select(u => new IndexVm
                {
                    Id = u.Id,
                    UserName = u.UserName,
                    ContactInfo = u.Email,
                    JobPosition = u.JobPosition,
                    Skills = u.GetSkills().ToList(),
                    ExpertKnowledge = u.Technologies.Select(t => t.Technology).ToList(),
                }).ToList();

            return View(data);
        }

        /// <summary>
        /// Returns data for user profile
        /// </summary>
        /// <param name="id"></param>
        /// <param name="technologyId"></param>
        /// <returns></returns>
        [HttpGet]
        public async Task<IActionResult> Visit(string id = null, int? technologyId = null)
        {
            ApplicationUser user = await this.GetCurrentUserAsync();

            var users = this.context.Users
                .Include(u => u.AssessmentsAsStudent).ThenInclude(a => a.Examiner)
                .Include(u => u.Technologies).ThenInclude(t => t.Technology);
            ApplicationUser profile = await users.SingleOrDefaultAsync(u => u.Id == id) ??
                                      await users.SingleOrDefaultAsync(u => u.Id == user.Id);

            if (profile == null)
            {
                return View("Error");
            }

            var techs = await this.context.Technology.ToListAsync();
            var selectedTech = techs.FirstOrDefault(t => t.Id == technologyId) ??
                               techs.FirstOrDefault();

            IList<ExamTask> tasks = null;
            IList<ExamAttempt> attempts = null;
            IList<ExamAttempt> bestAttempts = null;

            if (selectedTech != null)
            {
                tasks = await this.context.ExamTask.Where(t => t.TechnologyId == selectedTech.Id).ToListAsync();

                attempts = await this.context.ExamAttempt.Where(a => a.TechnologyId == selectedTech.Id && a.StudentId == profile.Id).ToListAsync();

                bestAttempts = attempts.Where(a => a.IsFinished)
                                       .GroupBy(a => a.Task.Id)
                                       .Select(g => g.OrderByDescending(a => a.ExamScore).First())
                                       .ToList();
            }

            bool self = profile.Id == user.Id;
            var model = new ProfileDetailsVm
            {
                Id = profile.Id,
                Self = self,
                UserName = profile.UserName,
                JobPosition = profile.JobPosition,
                ContactInfo = profile.Email,

                Technologies = techs,
                SelectedTechnology = selectedTech,

                ExpertKnowledge = profile.Technologies.Select(t => t.Technology).ToList(),

                Skills = profile.GetSkills().Concat(profile.AssessmentsAsStudent.Where(a => a.IsPassed is null)).ToList(),
                Assessments = profile.AssessmentsAsStudent.Where(a => a.TechnologyId == selectedTech.Id),

                AllAttempts = attempts ?? new List<ExamAttempt>(),
                BestAttempts = bestAttempts ?? new List<ExamAttempt>(),
                Tasks = self ? (tasks ?? new List<ExamTask>()) : null,
            };

            return View(model);
        }

        /// <summary>
        /// Loads user avatar from db
        /// </summary>
        /// <param name="id">User identifier</param>
        /// <returns></returns>
        public ActionResult GetAvatar(string id)
        {
            byte[] imageData = this.context.Users.Where(u => u.Id == id).Select(u => u.Avatar).FirstOrDefault();
            if (imageData != null)
            {
                return File(imageData, "image/png");
            }
            return NotFound();
        }

        [HttpGet]
        public async Task<IActionResult> Edit()
        {
            var user = await this.GetCurrentUserAsync();
            if (user == null)
                return RedirectToAction(nameof(Index));

            return View(new EditProfileVm { Id = user.Id, UserName = user.UserName, JobPosition = user.JobPosition });
        }

        public async Task<IActionResult> Edit(EditProfileVm model)
        {
            if (false == ModelState.IsValid)
            {
                return View(model);
            }

            var user = await this.GetCurrentUserAsync();
            if (user == null)
                return RedirectToAction(nameof(Index));

            user.UserName = model.UserName;
            user.JobPosition = model.JobPosition;
            if (model.AvatarImage != null)
            {
                using (var memoryStream = new System.IO.MemoryStream())
                {
                    await model.AvatarImage.CopyToAsync(memoryStream);
                    user.Avatar = memoryStream.ToArray();
                }
            }
            this.context.Update(user);
            this.context.SaveChanges();

            return RedirectToAction(nameof(Visit));
        }

        //
        // GET: /Manage/ChangePassword
        [HttpGet]
        public IActionResult ChangePassword()
        {
            return View();
        }

        //
        // POST: /Manage/ChangePassword
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ChangePassword(ChangePasswordVm model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            var user = await this.GetCurrentUserAsync();
            if (user != null)
            {
                var result = await this.userManager.ChangePasswordAsync(user, model.OldPassword, model.NewPassword);
                if (result.Succeeded)
                {
                    await _signInManager.SignInAsync(user, isPersistent: false);
                    _logger.LogInformation(3, "User changed their password successfully.");
                    return RedirectToAction(nameof(Visit), new { Message = ManageMessageId.ChangePasswordSuccess });
                }
                AddErrors(result);
                return View(model);
            }
            return RedirectToAction(nameof(Index), new { Message = ManageMessageId.Error });
        }

        //
        // GET: /Manage/SetPassword
        [HttpGet]
        public IActionResult SetPassword()
        {
            return View();
        }

        //
        // POST: /Manage/SetPassword
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SetPassword(SetPasswordVm model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var user = await this.GetCurrentUserAsync();
            if (user != null)
            {
                var result = await this.userManager.AddPasswordAsync(user, model.NewPassword);
                if (result.Succeeded)
                {
                    await _signInManager.SignInAsync(user, isPersistent: false);
                    return RedirectToAction(nameof(Index), new { Message = ManageMessageId.SetPasswordSuccess });
                }
                AddErrors(result);
                return View(model);
            }
            return RedirectToAction(nameof(Index), new { Message = ManageMessageId.Error });
        }

        #region Helpers

        private void AddErrors(IdentityResult result)
        {
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError(string.Empty, error.Description);
            }
        }

        public enum ManageMessageId
        {
            AddPhoneSuccess,
            AddLoginSuccess,
            ChangePasswordSuccess,
            SetTwoFactorSuccess,
            SetPasswordSuccess,
            RemoveLoginSuccess,
            RemovePhoneSuccess,
            Error
        }

        #endregion
    }
}

src/Axe/Views/Profiles/ChangePassword.cshtml
@model Axe.Models.ProfilesVm.ChangePasswordVm
@{
    ViewData["Title"] = "Change Password";
}

<h2>@ViewData["Title"].</h2>

<form asp-controller="Profiles" asp-action="ChangePassword" method="post" class="form-horizontal">
    <h4>Change Password Form</h4>
    <hr />
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="OldPassword" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="OldPassword" class="form-control" />
            <span asp-validation-for="OldPassword" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="NewPassword" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="NewPassword" class="form-control" />
            <span asp-validation-for="NewPassword" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="ConfirmPassword" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="ConfirmPassword" class="form-control" />
            <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <button type="submit" class="btn btn-default">Change password</button>
        </div>
    </div>
</form>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

src/Axe/Views/Profiles/Edit.cshtml
@model Axe.Models.ProfilesVm.EditProfileVm

@{
    ViewData["Title"] = "Edit";
}

<form asp-controller="Profiles" asp-action="edit" asp-method="post" enctype="multipart/form-data" class="form-horizontal" >
    <br />
    <div asp-valitation-summary="All" class="text-danger"></div>

    <div class="row"> 
        <div class="col-md-3">
            <img src="@Url.Action("GetAvatar", "Profiles", new { id = Model.Id })" alt="Profile Image" width="230" height="230" />
        </div>

        <div class="col-md-9">
            <div class="form-group">
                <label asp-for="UserName" class="control-label col-md-2"></label>
                <div class="col-md-10">
                    <input asp-for="UserName" class="form-control" />
                    <span asp-validation-for="UserName" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <label asp-for="JobPosition" class="col-md-2 control-label"></label>

                <div class="col-md-10">
                    <input asp-for="JobPosition" class="form-control" />
                    <span asp-for="JobPosition" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <label asp-for="AvatarImage" class="col-md-2 control-label"></label>
                
                <div class="form-group col-md-10">
                    <div class="col-md-2">
                        <label class="btn btn-default" for="AvatarImage">
                            <input id="AvatarImage" name="AvatarImage" type="file" style="display:none" accept=".png, .jpg"
                                   onchange="$('#upload-file-info').html(this.files[0].name)">
                            Browse
                        </label>
                    </div>
                    <div class="col-md-10">
                            <p id="upload-file-info"></p>
                        </div>
                    </div>
            </div>

            

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </div>
        </div>
    </div>

</form>

src/Axe/Views/Profiles/Index.cshtml
@model IEnumerable<Axe.Models.ProfilesVm.IndexVm>

@{
    ViewData["Title"] = "Index";
}

<br/>

@*https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/search*@
<form asp-controller="Profiles" asp-action="index" method="get" class="form-inline">    
    <div class="form-group">
        <label>Search</label>
        <input type="text" name="userFilter" value="@ViewData["userFilter"]" class="form-control"/>
        <input type="submit" value="GO" class="btn btn-primary"/>
    </div>
</form>
<hr/>

@foreach (var item in Model.Select((u, i) => new { user = u, idx = i % 3 }))
{
    @if (item.idx == 0)
    {
        @:<div class="row">
    }
    <div class="col-md-4">
        <a href="@Url.Action("Visit", "Profiles", new { id = item.user.Id })">
            <div class="row userCard">
                <div class="col-sm-2">                    
                    <img src="@Url.Action("GetAvatar", "Profiles", new { id = item.user.Id })" width="40" height="40" />
                </div>
                @*user card*@
                <div class="col-sm-10">                        
                    <h4>@item.user.UserName</h4>
                    
                    @if (item.user.JobPosition != null)
                    {
                        <p>@item.user.JobPosition</p>
                    }

                    @if (item.user.ContactInfo != item.user.UserName)
                    {
                        <p>@item.user.ContactInfo</p>
                    }

                    @if (item.user.ExpertKnowledge.Count > 0)
                    {
                        <h4>
                            @foreach (var t in item.user.ExpertKnowledge)
                            {
                                <label class="label label-primary">@t.Name</label>
                            }
                        </h4>
                    }

                    @if (item.user.Skills != null)
                    {
                        <p>
                            @foreach (var skill in item.user.Skills.Where(t => t.ExamScore.HasValue).OrderByDescending(t => t.ExamScore))
                            {
                                <kbd value="@skill.Technology.Id">
                                    @skill.Technology.Name
                                </kbd>

                                <code title="@skill.ExamDate">@skill.ExamScore</code>
                                @Html.Raw("&nbsp")
                            }
                        </p>
                    }
                </div>
            </div>
        </a>
    </div>

    @if (item.idx == 3)
    {
        @:</div>
    }
}
</div>

@*<table class="table">
    <thead>
        <tr>            
                <th>
                    @Html.DisplayNameFor(model => model.UserName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ContactInfo)
                </th>
            <th></th>
        </tr>
    </thead>
    <tbody>

@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.UserName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ContactInfo)
            </td>
            <td>
                @Html.ActionLink("Profiles", "Visit", new { id = item.Id })
            </td>
        </tr>
}
    </tbody>
</table>*@

src/Axe/Views/Profiles/SetPassword.cshtml
@model Axe.Models.ProfilesVm.SetPasswordVm
@{
    ViewData["Title"] = "Set Password";
}

<p class="text-info">
    You do not have a local username/password for this site. Add a local
    account so you can log in without an external login.
</p>

<form asp-controller="Profiles" asp-action="SetPassword" asp-route-returnurl="@ViewData["ReturnUrl"]" method="post" class="form-horizontal">
    <h4>Set your password</h4>
    <hr />
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="NewPassword" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="NewPassword" class="form-control" />
            <span asp-validation-for="NewPassword" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="ConfirmPassword" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="ConfirmPassword" class="form-control" />
            <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <button type="submit" class="btn btn-default">Set password</button>
        </div>
    </div>
</form>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}