src/Axe/Controllers/QuestionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using Axe.Models;
using Axe.Models.QuestionsVm;
using Axe.Managers;

namespace Axe.Controllers
{
    [Authorize]
    public class QuestionsController : ControllerExt
    {
        private IQuestionManager manager;

        public QuestionsController(UserManager<ApplicationUser> userManager, IQuestionManager manager) : base(userManager, null)
        {
            this.manager = manager;
        }

        [HttpGet]
        public async Task<IActionResult> Input(int? id = null, int? technologyId = null, int? questionType = null)
        {
            var q = new TaskQuestion
            {
                Id = id ?? 0,
                TechnologyId = technologyId,
                Type = (TaskQuestionType)(questionType ?? -1)
            };

            var request = await this.CreateRequest(q);

            var response = await this.manager.InputGet(request);

            if (response.Code == ResponseCode.NotFound)
            {
                return RedirectToAction("Index", "Technologies");
            }

            return View(response.Item);
        }

        [HttpPost]
        public async Task<IActionResult> Input(int id, QuestionInputVm questionVm, int? etp = null, string cmd = null)
        {
            cmd = cmd?.Trim()?.ToLower();

            var request = await this.CreateRequest(questionVm);

            Response<QuestionInputVm> response;

            if (cmd == "add")
            {
                response = this.manager.ChangeAnswers(request, true);
            }
            else if (cmd == "remove")
            {
                response = this.manager.ChangeAnswers(request, false);
            }
            else if (etp.HasValue)
            {
                response = this.manager.ChangeQuestionType(request, (TaskQuestionType)etp.Value);
            }
            else
            {
                response = await this.manager.InputPost(request);

                if (response.Code == ResponseCode.Success)
                {
                    if (id > 0)
                    {
                        return RedirectToAction(nameof(Details), new { id = id });
                    }
                    return RedirectToAction("Index", "Technologies", new { technologyId = response.Item.TechnologyId });
                }
            }

            if (response.Code == ResponseCode.NotFound)
            {
                return NotFound();
            }

            return View(response.Item);
        }

        /// <summary>
        /// Displays details about <see cref="TaskQuestion"/>
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<IActionResult> Details(int id)
        {
            var request = await this.CreateRequest(id);

            var response = await this.manager.DetailsGet(request);

            if (response.Code == ResponseCode.NotFound)
            {
                return this.NotFound();
            }

            return View(response.Item);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var request = await this.CreateRequest(id.Value);

            var response = await this.manager.DeleteGet(request);

            if (response.Code == ResponseCode.NotFound)
            {
                return NotFound();
            }

            return View(response.Item);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var request = await this.CreateRequest(id);

            var response = await this.manager.DeletePost(request);

            if (response.Code == ResponseCode.Success)
            {
                return RedirectToAction(nameof(TechnologiesController.Index), "Technologies");
            }

            if (response.Code == ResponseCode.ValidationError)
            {
                return View(nameof(Delete), response.Item);
            }

            return this.NotFound();
        }
    }
}

src/Axe/Views/Questions/Delete.cshtml
@model Axe.Models.TaskQuestion

@{
    ViewData["Title"] = "Delete Question";
}

<h4>Are you sure you want to delete this question?</h4>
<hr />

<div class="form-horizontal">
    <input type="hidden" asp-for="Id" />

    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

    <dl>
        <dt><label asp-for="Technology" class="control-label"></label></dt>
        <dd>@Html.DisplayFor(model => model.Technology.Name)</dd>

        <dt><label asp-for="Type" class="control-label"></label></dt>
        <dd>@Html.DisplayFor(model => model.Type)</dd>

        <dt><label asp-for="Text" class="control-label"></label></dt>
        <dd><p class="codeblock">@Html.DisplayFor(model => model.Text)</p></dd>

    </dl>

    <hr />
    <form asp-action="Delete">
        <div class="form-group row">
            <div class="col-md-10">
                @Html.ActionLink("Cancel", "Details", "Questions", new { id = Model.Id })
            </div>
            <div class="col-md-2">
                <input type="submit" value="Delete" class="btn btn-danger" />
            </div>
        </div>
    </form>
</div>

src/Axe/Views/Questions/Details.cshtml
@model Axe.Models.TaskQuestion

@{
    ViewData["Title"] = "Question Details";
}

<h4>Question details</h4>
<hr />

<div class="form-horizontal row">
    <dl class="col-md-6">
        <dt><label asp-for="Technology" class="control-label"></label></dt>
        <dd>@Html.DisplayFor(model => model.Technology.Name)</dd>

        <dt><label asp-for="Type" class="control-label"></label></dt>
        <dd>@Html.DisplayFor(model => model.Type)</dd>

        <dt><label asp-for="Author" class="control-label"></label></dt>
        <dd>@Html.DisplayFor(model => model.Author.UserName)</dd>

        <dt><label asp-for="Text" class="control-label"></label></dt>
        <dd><p class="codeblock md">@Model.Text</p></dd>

        <dt><label asp-for="Answers" class="control-label"></label></dt>
        <br />
        <dd >            
            <table class="table col-md-6">
                <tbody>
                    @foreach (var a in Model.Answers)
                    {
                        <tr>
                            <td class="codeblock">@a.Text</td>
                            <td>
                                @if (a.Score > 0)
                                {
                                    <span class="label label-success">+@a.Score</span>
                                }
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </dd>
    </dl>
</div>

<hr />
<div class="form-group row">
    <div class="col-md-2">
        @Html.ActionLink("Back to Technologies", "Index", "Technologies", new { technologyId = Model.TechnologyId })
    </div>
    <div class="btn-group">
        @Html.ActionLink("Edit", "Input", "Questions", new { id = Model.Id, technologyId = Model.TechnologyId }, new { @class = "btn btn-primary" })
        @Html.ActionLink("Delete", "Delete", "Questions", new { id = Model.Id }, new { @class = "btn btn-default" })
    </div>
</div>

src/Axe/Views/Questions/Input.cshtml
@model Axe.Models.QuestionsVm.QuestionInputVm

@{
    ViewData["Title"] = "Question Editor";
}

@section Scripts
{    
    <script src="~/js/questions.input.js"></script>
}

<h2>Ask a question</h2>

<form asp-action="Input" asp-controller="Questions" method="post">

    <div class="form-group">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="Id" />

        <input type="hidden" id="EditorType" name="EditorType" value="@Model.EditorType" />

        <div class="form-group">
            <label asp-for="TechnologyId" class="control-label"></label>
            <div class="row">
                <div class="col-md-6">
                    <select asp-for="TechnologyId" class="form-control" asp-items="@Model.Technologies"></select>
                </div>
            </div>
            <span asp-validation-for="TechnologyId" class="text-danger"></span>
        </div>

        <label asp-for="Text" class="control-label"></label>

        <div class="row">
            <div class="col-md-6 form-group">
                <textarea asp-for="Text" class="form-control" rows="16" id="rawText"></textarea>
                <span asp-validation-for="Text" class="text-danger"></span>
            </div>

            <div class="col-md-6 codeblock">
                <div class="table-responsive" id="decoratedText">
                    @Model.Text
                </div>
            </div>
        </div>
    </div>

    <div class="row form-group">
        <div class="btn-group col-md-8">
            <button class="btn btn-default" type="submit" value="0" name="etp">
                <span class="glyphicon glyphicon-tags"></span> &nbsp; Multi Choice
            </button>
            <button class="btn btn-default" type="submit" value="1" name="etp">
                <span class="glyphicon glyphicon-tag"></span>  &nbsp; Single Choice
            </button>
            <button class="btn btn-default" type="submit" value="2" name="etp">
                <span class="glyphicon glyphicon-duplicate"></span> &nbsp; Multi Line
            </button>
            <button class="btn btn-default" type="submit" value="3" name="etp">
                <span class="glyphicon glyphicon-file"></span> &nbsp; Single Line
            </button>
            <button class="btn btn-default" type="submit" value="4" name="etp">
                <span class="glyphicon glyphicon-sort-by-attributes"></span> &nbsp; Priority
            </button>
        </div>
    </div>


    @if (Model.WithUserInput)
    {
        <div class="row">
            <div class="form-group col-md-6">
                <label class="control-label">Answer text</label>

                <input type="hidden" asp-for="@Model.Answers[0].Id" />
                <input type="hidden" asp-for="@Model.Answers[0].Value" />
                @if (Model.EditorType == Axe.Models.TaskQuestionType.SingleLine)
                {
                    <input asp-for="@Model.Answers[0].Text" class="form-control col-md-6" />
                }
                else
                {
                    <textarea asp-for="@Model.Answers[0].Text" class="form-control col-md-6" rows="4"></textarea>
                }
            </div>

            <div class="form-group col-md-6">
                <label class="control-label">Score</label>
                <div>                    
                    <input asp-for="@Model.Answers[0].Score" class="form-control answer-score"/>
                </div>
            </div>
        </div>
    }
    else
    {
        <div class="form-group">

            <div class="row form-group">
                <div class="col-md-10">
                    <label class="control-label">Answer text</label>
                </div>

                <div class="col-md-1">
                    <label class="control-label">Value</label>
                </div>

                <div class="col-md-1">
                    <label class="control-label">Score</label>
                </div>
            </div>

            @for (int i = 0; i < Model.Answers.Count; i++)
            {
                <div class="row form-group">

                    <div class="col-md-10">
                        <input type="hidden" asp-for="@Model.Answers[i].Id" />
                        <input asp-for="@Model.Answers[i].Text" class="form-control" />
                        <span asp-validation-for="@Model.Answers[i].Text" class="text-danger"></span>
                    </div>

                    <div class="col-md-1">
                        @if (Model.EditorType == Axe.Models.TaskQuestionType.SingleChoice)
                        {
                            <input asp-for="SelectedAnswer" type="radio" value="@i" />
                        }
                        else if (Model.EditorType == Axe.Models.TaskQuestionType.MultiChoice)
                        {
                            @Html.CheckBoxFor(m => m.Answers[i].IsCorrect)
                        }
                        else if (Model.EditorType == Axe.Models.TaskQuestionType.PrioritySelection)
                        {
                            <select asp-for="@Model.Answers[i].Value" asp-items="@Model.PriorityOptions">
                                <option></option>
                            </select>
                        }
                    </div>

                    <div class="col-md-1">                        
                        <input asp-for="@Model.Answers[i].Score" class="form-control answer-score" min="0" max="100"/>
                        <span asp-validation-for="@Model.Answers[i].Score" class="text-danger"></span>
                    </div>
                </div>
            }
        </div>

        <div class="row">
            <div class="btn-group col-md-3">
                <input type="submit" value="&nbsp;Add&nbsp;" name="cmd" class="btn btn-default" title="Add an answer" />
                @if (Model.Answers.Count > 1)
                {
                    <input type="submit" value="Remove" name="cmd" class="btn btn-default" title="Remove last answer" />
                }                
            </div>
            <div class="col-md-1 col-md-offset-8" title="Total score">
                <span id="totalScore" class="label"></span>                
            </div>
        </div>            
    }

    <hr />
    <div class="row">
        <div class="col-md-2">
            @Html.ActionLink("Back to Technologies", "Index", "Technologies", new { technologyId = Model.TechnologyId })
        </div>
        <input type="submit" value="Save" name="cmd" class="btn btn-primary" />
    </div>
</form>