src/Axe/Controllers/TasksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using Axe.Models;
using Axe.Models.ExamTasksVm;
using Axe.Managers;

namespace Axe.Controllers
{
    [Authorize]
    public class TasksController : ControllerExt
    {
        private IExamTaskManager manager;

        public TasksController(UserManager<ApplicationUser> userManager, IExamTaskManager manager) : base(userManager, null)
        {
            this.manager = manager;
        }

        public async Task<IActionResult> Details(int? id)
        {
            var request = await this.CreateRequest(id);
            var response = await this.manager.DetailsGet(request);

            if (response.Code == ResponseCode.NotFound)
            {
                return NotFound();
            }

            return View(response.Item);
        }

        public async Task<IActionResult> Input(int? id, int? technologyId = null)
        {
            var request = await this.CreateRequest(new ExamTask { Id = id ?? 0, TechnologyId = technologyId });

            var response = await this.manager.InputGet(request);

            if (response.Code == ResponseCode.Success)
            {
                return View(response.Item);
            }

            return this.NotFound();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Input(int id, TaskInputVm taskInput)
        {
            if (id != taskInput.Id)
            {
                return NotFound();
            }

            var request = await this.CreateRequest(taskInput);

            var response = await this.manager.InputPost(request);

            if (response.Code == ResponseCode.Success)
            {
                return RedirectToAction("Index", "Technologies", new { technologyId = response.Item.TechnologyId });
            }

            return View(response.Item);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var request = await this.CreateRequest(id.Value);

            var response = await this.manager.DeleteGet(request);

            if (response.Code == ResponseCode.NotFound)
            {
                return NotFound();
            }

            return View(response.Item);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var request = await this.CreateRequest(id);

            var response = await this.manager.DeletePost(request);

            if (response.Code == ResponseCode.Success)
            {
                return RedirectToAction(nameof(TechnologiesController.Index), "Technologies");
            }

            if (response.Code == ResponseCode.ValidationError)
            {
                return View(nameof(Delete), response.Item);
            }

            return this.NotFound();
        }
    }
}

src/Axe/Views/Tasks/Create.cshtml
@model Axe.Models.ExamTask

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<form asp-action="Create">
    <div class="form-horizontal">
        <h4>ExamTask</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="Title" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Objective" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Objective" class="form-control" />
                <span asp-validation-for="Objective" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="TechnologyId" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <select asp-for="TechnologyId" class ="form-control" asp-items="ViewBag.TechnologyId"></select>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

src/Axe/Views/Tasks/Delete.cshtml
@model Axe.Models.ExamTask

@{
    ViewData["Title"] = "Delete Task";
}

<h4>Are you sure you want to delete this test task?</h4>
<hr />

<div class="form-horizontal">
    <input type="hidden" asp-for="Id" />
    
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

    <dl>
        <dt><label asp-for="Title" class="control-label"></label></dt>
        <dd>@Html.DisplayFor(model => model.Title)</dd>

        <dt><label asp-for="Objective" class="control-label"></label></dt>
        <dd>@Html.DisplayFor(model => model.Objective)</dd>

        <dt><label asp-for="Technology" class="control-label"></label></dt>
        <dd>@Html.DisplayFor(model => model.Technology.Name)</dd>
    </dl>
    
    <hr />
    <form asp-action="Delete" method="post">
        <div class="form-group row">
            <div class="col-md-10">
                @Html.ActionLink("Cancel", "Details", "Tasks", new { id = Model.Id })
            </div>
            <div class="col-md-2">
                <input type="submit" value="Delete" class="btn btn-danger" />
            </div>
        </div>
    </form>
</div>

src/Axe/Views/Tasks/Details.cshtml
@model Axe.Models.ExamTask

@{
    ViewData["Title"] = "Task Details";
}

<h4>@Model.Title</h4>
<h4>@Model.Objective</h4>

<hr />

<div class="form-horizontal row">
    <dl class="col-md-6">
        <dt><label asp-for="Title" class="control-label"></label></dt>
        <dd>@Html.DisplayFor(model => model.Title)</dd>

        <dt><label asp-for="Objective" class="control-label"></label></dt>
        <dd>@Html.DisplayFor(model => model.Objective)</dd>

        <dt><label asp-for="Technology" class="control-label"></label></dt>
        <dd>@Html.DisplayFor(model => model.Technology.Name)</dd>

        <dt><label asp-for="PassingThreshold" class="control-label"></label></dt>
        <dd>@Html.DisplayFor(model => model.PassingThreshold)</dd>

        <dt><label asp-for="Questions" class="control-label"></label></dt>
        <dd>
            <table class="table table-striped">
                <tbody>
                    @foreach(var q in Model.Questions)
                    {
                        <tr>
                            <td class="codeblock">@q.Question.Preview</td>
                            <td>@q.Question.Type</td>
                        </tr>
                    }
                </tbody>
            </table>
        </dd>
    </dl>
</div>

<hr />
<div class="form-group row">
    <div class="col-md-2">
        @Html.ActionLink("Back to Technologies", "Index", "Technologies", new { technologyId = Model.TechnologyId })
    </div>
    <div>
        <div class="btn-group">
            @Html.ActionLink("Edit", "Input", "Tasks", new { id = Model.Id, technologyId = Model.TechnologyId }, new { @class = "btn btn-primary" })
            @Html.ActionLink("Delete", "Delete", "Tasks", new { id = Model.Id }, new { @class="btn btn-default" })
        </div>
    </div>
</div>

src/Axe/Views/Tasks/Input.cshtml
@using Axe.Models
@model Axe.Models.ExamTasksVm.TaskInputVm

@{
    ViewData["Title"] = "Task Editor";
}

@section Scripts
{    
    <script src="~/js/tasks.input.js"></script>
}

<h2>Create @Model.TechnologyName Test Task</h2>

<form asp-action="Input">
    <div class="form-group">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="@Model.Id" />
        <input type="hidden" asp-for="@Model.TechnologyId" />

        <label asp-for="Title" class="control-label"></label>

        <div class="form-group row">            
            <div class="col-md-6">
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
        </div>

        <label asp-for="Objective" class="control-label"></label>

        <div class="form-group row">            
            <div class="col-md-6">
                <input asp-for="Objective" class="form-control" />                
                <span asp-validation-for="Objective" class="text-danger"></span>
            </div>
        </div>

        <label asp-for="IsDemonstration" class="control-label"></label>

        <div class="form-group row">
            <div class="col-md-6">
                @Html.CheckBoxFor(m => m.IsDemonstration)
                <span asp-validation-for="IsDemonstration" class="text-danger"></span>
            </div>
        </div>

        <label asp-for="PassingThreshold" class="control-label"></label>

        <div class="form-group row">
            <div class="col-md-6">
                @Html.EditorFor(m => m.PassingThreshold)
                <span asp-validation-for="PassingThreshold" class="text-danger"></span>
            </div>
        </div>

        <label class="control-label">Total Score</label>
        <div class="form-group">
            <span id="totalScore" class="label">0</span>
        </div>

        <label asp-for="Questions" class="control-label"></label>

        <div class="form-group row">                        
            <div class="col-md-3">
                <input id="questionsSearch" type="text" class="form-control" placeholder="Search">
            </div>

            <label id="searchReset" class="btn btn-default" title="Clear search"><span class="glyphicon glyphicon-flash"></span></label>            
        </div>

        <div class="form-group row">
            <div class="table-responsive">
                <table class="table" id="questionsTable">
                    <tbody>
                        @for (int i = 0; i < Model.Questions.Count; i++)
                        {
                            <tr title="@Model.Questions[i].Type @Model.Questions[i].Text">
                                <td>
                                    <input type="hidden" asp-for="@Model.Questions[i].Id" />                                    
                                    <input type="checkbox" asp-for="@Model.Questions[i].IsSelected" class="question-selector"/>
                                </td>                                
                                <td>
                                    <p>@Model.Questions[i].Preview</p>
                                </td>
                                <td>
                                    +<span class="question-score">@Model.Questions[i].Score</span>
                                </td>
                                <td>
                                    @switch (Model.Questions[i].Type)
                                    {
                                        case TaskQuestionType.MultiChoice: <span class="glyphicon glyphicon-tags">&nbsp; MultiChoice</span>
                                        break;
                                        case TaskQuestionType.SingleChoice: <span class="glyphicon glyphicon-tag">&nbsp; SingleChoice</span>
                                        break;
                                        case TaskQuestionType.MultiLine: <span class="glyphicon glyphicon-duplicate">&nbsp; MultiLine</span>
                                        break;
                                        case TaskQuestionType.SingleLine: <span class="glyphicon glyphicon-file">&nbsp; SingleLine</span>
                                        break;
                                        case TaskQuestionType.PrioritySelection: <span class="glyphicon glyphicon-sort-by-attributes">&nbsp; Priority</span> 
                                        break;
                                    }
                                </td>
                            </tr>

                        }
                    </tbody>
                </table>
            </div>
        </div>

        <hr />
        <div class="form-group row">
            <div class="col-md-10">
                @Html.ActionLink("Back to Technologies", "Index", "Technologies", new { technologyId = Model.TechnologyId })
            </div>
            <div class="col-md-2">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
</form>