src/Axe/Models/Technology.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace Axe.Models
{
    /// <summary>
    /// Class represents a Technology abstraction
    /// </summary>
    public class Technology
    {
        /// <summary>
        /// Gets ort sets identifier
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets technology name
        /// </summary>
        [Required]
        [MaxLength(1024)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets short description of a technology
        /// </summary>
        [MaxLength(1024)]
        [Required]
        public string InformationText { get; set; }

        /// <summary>
        /// Gets or sets list of experts
        /// </summary>
        public ICollection<ExpertTechnologyLink> Experts { get; set; }

        /// <summary>
        /// Gets or sets list of exam attempts made by users in this technology
        /// </summary>
        public ICollection<ExamAttempt> Attempts { get; set; }

        /// <summary>
        /// Gets or sets list of skill assessments in this technology
        /// </summary>
        public ICollection<SkillAssessment> Assessments { get; set; }

        /// <summary>
        /// Gets or sets template for code block
        /// </summary>
        public string Template { get; set; }
    }
}

src/Axe/Controllers/TechnologiesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Axe.Models;
using Axe.Managers;

namespace Axe.Controllers
{
    [Authorize]
    public class TechnologiesController : ControllerExt
    {
        private ITechnologyManager manager;

        public TechnologiesController(UserManager<ApplicationUser> userManager, ITechnologyManager manager) : base(userManager, null)
        {
            this.manager = manager;
        }

        /// <summary>
        /// Returns a list of technologies available for current user with details about selected technology
        /// </summary>
        /// <param name="technologyId"></param>
        /// <returns></returns>
        public async Task<IActionResult> Index(int? technologyId = null)
        {
            var request = await this.CreateRequest(technologyId);

            var response = await this.manager.Index(request);

            return View(response.Item);
        }

        /// <summary>
        /// Returns page to create or edit <see cref="Technology"/> entity
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        public async Task<IActionResult> Input(int? id)
        {
            var request = await this.CreateRequest(id);

            var response = await this.manager.InputGet(request);

            if (response.Code == ResponseCode.NotFound)
            {
                return NotFound();
            }

            return View(response.Item);
        }

        /// <summary>
        /// Submits <see cref="Technology"/> entity for creation or edit
        /// </summary>
        /// <param name="id"></param>
        /// <param name="technologyInput"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Input(int? id, [Bind("Id,Name,InformationText")] Technology technologyInput)
        {
            if (id != technologyInput.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                var request = await CreateRequest(technologyInput);

                var response = await this.manager.InputPost(request);

                if (response.Code == ResponseCode.NotFound)
                {
                    return NotFound();
                }

                if (response.Code == ResponseCode.Success)
                {
                    return RedirectToAction("Index", new { technologyId = technologyInput.Id });
                }
            }
            return View(technologyInput);
        }

        /// <summary>
        /// Adds a user to technology expert list
        /// </summary>
        public async Task<IActionResult> IncludeExpert(string id, int technologyId)
        {
            var request = await this.CreateRequest(new ExpertTechnologyLink { UserId = id, TechnologyId = technologyId });

            await this.manager.IncludeExpert(request);

            return RedirectToAction("Index", new { technologyId });
        }

        /// <summary>
        /// Removes a user from technology experts list
        /// </summary>
        public async Task<IActionResult> ExcludeExpert(string id, int technologyId)
        {
            var request = await this.CreateRequest(new ExpertTechnologyLink { UserId = id, TechnologyId = technologyId });

            await this.manager.ExcludeExpert(request);

            return RedirectToAction("Index", new { technologyId });
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var request = await this.CreateRequest(id.Value);

            var response = await this.manager.DeleteGet(request);

            if (response.Code == ResponseCode.NotFound)
            {
                return NotFound();
            }

            return View(response.Item);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var request = await this.CreateRequest(id);

            var response = await this.manager.DeletePost(request);

            if (response.Code == ResponseCode.Success)
            {
                return RedirectToAction(nameof(Index));
            }

            if (response.Code == ResponseCode.ValidationError)
            {
                return View(nameof(Delete), response.Item);
            }

            return this.NotFound();
        }
    }
}

src/Axe/Views/Technologies/Delete.cshtml
@model Axe.Models.Technology

@{
    ViewData["Title"] = "Delete Technology";
}

<h4>Are you sure you want to delete @Model.Name?</h4>
<hr />

<div class="form-horizontal">
    <input type="hidden" asp-for="Id" />

    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

    <dl>
        <dt><label asp-for="Name" class="control-label"></label></dt>
        <dd>@Html.DisplayFor(model => model.Name)</dd>

        <dt><label asp-for="InformationText" class="control-label"></label></dt>
        <dd><span class="codeblock">@Html.DisplayFor(model => model.InformationText)</span></dd>
    </dl>

    <hr />
    <form asp-action="Delete">
        <div class="form-group row">
            <div class="col-md-10">
                @Html.ActionLink("Cancel", "Index", "Technologies", new { technologyId = Model.Id })
            </div>

            <div class="form-actions no-color col-md-2">
                <input type="submit" value="Delete" class="btn btn-danger" />
            </div>
        </div>
    </form>
</div>

src/Axe/Views/Technologies/Index.cshtml
@using Axe.Models
@model Axe.Models.TechnologiesVm.TechnologiesIndexVm

@{
    ViewData["Title"] = "Technologies";
}

<br />

@if (Model.SelectedTechnology != null)
{
    <div class="row">
        <div class="jumbotron">
            <h2><kbd>@Model.SelectedTechnology.Name</kbd></h2>
            <p class="codeblock md">@Model.SelectedTechnology.InformationText</p>
        </div>
    </div>
}

<div class="row">
    <div class="btn-group">
        @Html.ActionLink("Add", "Input", "Technologies", null, new { @class = "btn btn-primary" })
        @Html.ActionLink("Edit", "Input", "Technologies", new { id = Model.SelectedTechnology?.Id }, new { @class = "btn btn-primary" })
        @Html.ActionLink("Delete", "Delete", "Technologies", new { id = Model.SelectedTechnology?.Id }, new { @class = "btn btn-default" })
    </div>
    <hr />
</div>

<div class="row">

    <div class="col-md-2">
        <form asp-controller="Profiles" asp-action="Visit">
            <ul class="nav nav-pills nav-stacked">

                @foreach (var t in Model.Technologies)
                {
                    string active = t.Id == Model.SelectedTechnology?.Id ? "active" : null;
                    <li class="@active">@Html.ActionLink(t.Name, "Index", "Technologies", new { technologyId = t.Id })</li>
                }
            </ul>
        </form>
    </div>

    <div class="col-md-10">
        <ul id="techTabs" class="nav nav-tabs nav-justified">
            <li class="active"><a data-toggle="tab" href="#menuQuestions">Questions</a></li>
            <li><a data-toggle="tab" href="#menuExams">Exams</a></li>
            <li><a data-toggle="tab" href="#menuExperts">Experts</a></li>
            <li><a data-toggle="tab" href="#menuMonitor">Monitor</a></li>
        </ul>

        <div class="tab-content">
            @*exam question*@

            <div id="menuQuestions" class="tab-pane fade in active">
                <br />
                <div class="table-responsive">                    
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>
                                    <span class="glyphicon glyphicon-th"></span>
                                </th>
                                <th>Question</th>
                                <th>Type</th>
                                <th>Author</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.Questions.Select((q, i) => new { question = q, idx = i + 1 }))
                            {
                                <tr>
                                    <td>@item.idx</td>
                                    <td title="@item.question.Text">@item.question.Preview</td>
                                    <td>
                                        @switch (@item.question.Type)
                                        {
                                            case TaskQuestionType.MultiChoice: <span class="glyphicon glyphicon-tags">&nbsp; Multi-Choice</span>
                                            break;
                                            case TaskQuestionType.SingleChoice: <span class="glyphicon glyphicon-tag">&nbsp; Single-Choice</span>
                                            break;
                                            case TaskQuestionType.MultiLine: <span class="glyphicon glyphicon-duplicate">&nbsp; Multi-Line</span>
                                            break;
                                            case TaskQuestionType.SingleLine: <span class="glyphicon glyphicon-file">&nbsp; Single-Line</span>
                                            break;
                                            case TaskQuestionType.PrioritySelection: <span class="glyphicon glyphicon-sort-by-attributes">&nbsp; Priority</span>
                                            break;
                                        }
                                    </td>
                                    <td>@item.question.Author?.UserName</td>
                                    <td>
                                        @Html.ActionLink("details", "Details", "Questions", new { id = item.question.Id })
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>

                @if (Model.SelectedTechnology != null)
                {
                    <br />
                    @Html.ActionLink("Add", "Input", "Questions", new { technologyId = Model.SelectedTechnology?.Id }, new { @class = "btn btn-primary" })
                }
            </div>

            @*exams*@
            <div id="menuExams" class="tab-pane fade">
                <br />
                <div class="table-responsive">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>
                                    <span class="glyphicon glyphicon-th"></span>
                                </th>
                                <th>Title</th>
                                <th>Objective</th>
                                <th>Demo</th>
                                <th>Author</th>
                                <th>Questions</th>
                                <th>Threshold</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.Exams.Select((q, i) => new { exam = q, idx = i + 1 }))
                            {
                                <tr>
                                    <td>@item.idx</td>
                                    <td>@item.exam.Title</td>
                                    <td>@item.exam.Objective</td>
                                    <td>
                                        @if (item.exam.IsDemonstration)
                                        {
                                            <span class="glyphicon glyphicon-flag"></span>
                                        }
                                    </td>
                                    <td>@item.exam.Author?.UserName</td>
                                    <td>@item.exam.Questions?.Count</td>
                                    <td>@item.exam.PassingThreshold %</td>
                                    <td>
                                        @Html.ActionLink("details", "Details", "Tasks", new { id = item.exam.Id })
                                    </td>
                                </tr>

                            }
                        </tbody>
                    </table>
                </div>

                @if (Model.SelectedTechnology != null)
                {
                    <br />
                    @Html.ActionLink("Add", "Input", "Tasks", new { technologyId = Model.SelectedTechnology?.Id }, new { @class = "btn btn-primary" })
                }
            </div>

            @*Experts*@
            <div id="menuExperts" class="tab-pane fade">
                <br />
                <div class="table-responsive">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>User</th>
                                <th>Email</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var e in Model.Experts)
                            {
                                <tr>
                                    <td>@Html.ActionLink(e.UserName, "Visit", "Profiles", new { id = e.Id })</td>
                                    <td>@e.Email</td>
                                    <td>
                                        @{
                                            string category = e.IsExpert ? "default" : "primary";
                                            string linkName = e.IsExpert ? "Exclude" : "Include";
                                            <a href="@Url.Action(linkName+"Expert", new { id = e.Id, technologyId = Model.SelectedTechnology?.Id})">
                                                <label class="btn btn-@category">
                                                    @linkName
                                                </label>
                                            </a>
                                        }
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>

            @*Active exams*@
            <div id="menuMonitor" class="tab-pane fade">
                <br />
                <div class="table-responsive">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>User</th>
                                <th>Exam Time</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var a in Model.ActiveAttempts)
                            {
                                <tr>
                                    <td>@Html.ActionLink(a.Student.UserName, "Visit", "Profiles", new { id = a.Student.Id })</td>
                                    <td>@a.ExamDate</td>
                                    <td>@Html.ActionLink("View", "Result", "Exams", new { id = a.Id })</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

src/Axe/Views/Technologies/Input.cshtml
@model Axe.Models.Technology

@{
    ViewData["Title"] = Model.Name ?? "Technology Editor";
}

<h2>Write technology description</h2>

<form asp-action="Input">
    <div class="form-horizontal">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="Id" />

        <label asp-for="Name" class="control-label"></label>

        <div class="form-group">
            <div class="col-md-6">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>

        <label asp-for="InformationText" class="control-label"></label>

        <div class="form-group">
            <div class="col-md-6">
                <textarea asp-for="InformationText" rows="8" cols="128" class="form-control"></textarea>
                <span asp-validation-for="InformationText" class="text-danger"></span>
            </div>
        </div>
    </div>


    <hr />
    <div class="form-group row">
        <div class="col-md-10">
            @Html.ActionLink("Back to Technologies", "Index", "Technologies", new { technologyId = Model.Id })
        </div>

        <div class="col-md-2">
            <input type="submit" value="Save" class="btn btn-primary" />
        </div>
    </div>

</form>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}